name: CI for MERN Vehicle Rental System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  merge-check:
    name: Merge Approval Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Backend Dependencies
        run: |
          if [ -d "api" ]; then cd api && npm install; fi

      - name: Install Frontend Dependencies
        run: |
          if [ -d "client" ]; then cd client && npm install; fi

      - name: Require Checks Before Merging
        run: echo "✅ No conflicts detected. Ready to merge!"
