name: CI for MERN Vehicle Rental System

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  merge-check:
    name: Merge Approval Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Backend Dependencies
        run: |
          if [ -d "api" ]; then cd api && npm install; fi

      - name: Install Frontend Dependencies
        run: |
          if [ -d "client" ]; then cd client && npm install; fi

      - name: Check for Tests
        run: |
          HAS_TESTS=false
          if [ -d "api" ] && [ -f "api/package.json" ] && grep -q '"test":' api/package.json; then HAS_TESTS=true; fi
          if [ -d "client" ] && [ -f "client/package.json" ] && grep -q '"test":' client/package.json; then HAS_TESTS=true; fi
          echo "HAS_TESTS=$HAS_TESTS" >> $GITHUB_ENV

      - name: Run Tests if Available
        if: env.HAS_TESTS == 'true'
        run: |
          if [ -d "api" ] && [ -f "api/package.json" ]; then cd api && npm test; fi
          if [ -d "client" ] && [ -f "client/package.json" ]; then cd client && npm test; fi

      - name: Basic Test if No Tests Exist
        if: env.HAS_TESTS == 'false'
        run: echo "No tests found. Running a basic check..."

      - name: Require Checks Before Merging
        run: echo "✅ No conflicts detected. Ready to merge!"
